var lists = exports;
lists.boc = [
	'3 Movie Passes (Expired)',
	'4000 Napkins',
	'5 Speaker Mounting Kit',
	'6lbs. bag of cocaine',
	'75-pound BicepNow Dumbell',
	'9v Battery',
	'AA Batteries (24 Count)',
	'AAA Batteries (8 Count)',
	'Alcohol Breath Tester',
	'Bamboo Panflute',
	'Bar Crawl Bingo',
	'Baywatch Barbie Backpack',
	'Big Bang Theory Season 3 (Opened)',
	'Black Portable Speakers',
	'Blackberry Bold Screen Replacement Kit',
	'Blue Duffel Bag',
	'Cyber Acoustics Leather Cover for Samsung Galaxy Tablet',
	'Diablo 2',
	'Earmuffs',
	'English Grammar For Dummies [Paperback]',
	'Electric Fly Swatter',
	'Fondue Pot',
	'FootFlush Kit',
	'Guard Dog L',
	'Guard Dog M',
	'Guard Dog S',
	'Guard Dog XL',
	'Guard Dog XS',
	'HDMI Cable',
	'Headphone splitters',
	'Hole Punch',
	'iPod Classic 4th Generation 20GB',
	'iPowerPro Universal Auto/Airplane Adapter',
	'Kindle Cover',
	'Leather Case for Galaxy Tab',
	'Lint Roller',
	'LOST Season 4',
	'Martini Glass (Set of 6)',
	'Microfiber Fuzzy Socks',
	'Microsoft Windows 95',
	'Microsoft Zune (Refurb, not working, as usual)',
	'Mighty Kite',
	'Perfect Pushup',
	'Pet Basics Pet Blanket',
	'DJ Pinky T Signatue DJ Table',
	'Refurbished Toshiba Satellite Laptop 320GB',
	'Roomba',
	'Sandisk USB Cable',
	'Sanyo AAA Batteries 4 Pack',
	'Screaming Woot Monkey-Flames',
	'Seattle Air',
	'Sennheiser PC300 G4ME Earbuds',
	'Sex in the City Season 2',
	'Simply Citrus Bar Soap',
	'Small Zebra Tote Bag',
	'Snow Man digital picture frame ornament',
	'Star Trek: The Role Playing Game',
	'Stress Ball',
	'T-shirt Black S Adult Women\'s',
	'T-shirt Blue L Adult',
	'T-shirt Green XL Adult',
	'T-shirt Grey M Adult Women\'s',
	'T-shirt Orange S Adult',
	'T-shirt Pink XL Adult Women\'s',
	'T-shirt Purple L Adult Women\'s',
	'T-shirt Red M Adult',
	'Tabletop Tripod',
	'Team Fortress 2 Guest Pass',
	'Terrific Turkey Thermometer',
	'Texas Air',
	'TomTom XXL 550 (Refurbished)',
	'Tote Bag',
	'Toy Story Canvas Paint Set',
	'USB Extension Cable',
	'Used Deodorant',
	'Used Golf Balls',
	'Wine Tote',
	'Women\'s XS Tshirt White',
	'Woot Calendar',
	'Woot Cedar Plank',
	'Woot Letter'
];

lists.facts = [
	'A bear’s normal heartbeat is 40 beats per minute. A hibernating bear’s heart rate drops to 8 bpm.',
	'A full day on the moon, from one sunrise to the next, lasts about 29 Earth days on average.',
	'A group of monkeys is called a "troop."',
	'A monkey is any primate that is not a human, prosimian, or ape.',
	'A puppy is born blind, deaf, and toothless.',
	'A wolf pup’s eyes are blue at birth. Their eyes turn yellow by the time they are eight months old.',
	'Although wolves are usually afraid of humans, they will respond to human howls',
	'Approximately 1-2% of humans, or about two in 100 people in the world, have red hair.',
	'Approximately every 11 years, the sun reverses its overall magnetic polarity: its north magnetic pole becomes a south pole, and vice versa.',
	'At its core, the sun’s temperature is about 15 million degrees Celsius',
	'Barbra Streisand has sold more records (140 million) than Pearl Jam, Johnny Cash, and Tom Petty combined',
	'Bears are bowlegged.',
	'Bears can run up to 40 miles per hour, fast enough to catch a running horse. The fastest known human alive today is Usain Bolt, who can run 27mph.',
	'Celine Dion\'s “Falling Into You” sold more copies than any Queen, Nirvana, or Bruce Springsteen record',
	'Contrary to popular belief, David Bowie\'s eyes aren\'t two different colours. The truth is that one pupil has been permanently enlarged ever since he got punched in the face at school.',
	'Creed has sold more records in the US than Jimi Hendrix',
	'Dalmatians are completely white at birth.',
	'Dog nose prints are as unique as human finger prints and can be used to identify them.',
	'Dogs have sweat glands in between their paws.',
	'Dolphin teeth are used for grasping, not chewing. They have no jaw muscles for chewing.',
	'Dolphins may kill sharks by ramming them with their beaks.',
	'Earth was originally born as a twin to the planet Theia, which was about half as wide as Earth and roughly the size of Mars. The two planets shared an orbit for several million years until they collided. Earth absorbed Theia, and the remaining debris eventually coagulated into Earth’s moon. The mass donated by Theia gave Earth the gravity necessary to sustain a substantial atmosphere.',
	'FIFA 2001 is the first and only game to date to use a "scratch and sniff" CD. The disc smelt of turf.',
	'Flo Rida\'s “Low” has sold 8 million copies – the same as The Beatles\' “Hey Jude”',
	'Halo 2 is the bestselling Xbox title ever, selling some eight million copies. It’s closely followed by five million for the original Halo.',
	'In the original arcade Donkey Kong game, Mario was called Jumpman and he was a carpenter, not a plumber.',
	'Katy Perry holds the same record as Michael Jackson for most number one singles from an album',
	'Ke$ha\'s “Tik-Tok” sold more copies than ANY Beatles single',
	'Koala bears are not bears at all and are not related to the bear family. They are marsupials.',
	'Led Zeppelin, REM, and Depeche Mode have never had a number one single, Rihanna has 10',
	'Madonna started her career as a drummer in an 80s band called The Breakfast Club. She went onto become part of another group called Emmy before finally deciding to go it alone as a singer.',
	'Mercury and Venus are the only planets in our solar system that have no moon.',
	'Monkeys are most easily distinguished from apes by their tails. Apes have no tails.',
	'Most monkeys eat both animals and plants. Some also eat dirt.',
	'Most species of toothed whales live in matrilineal pods dominated by females; males stay with the pods only shortly to mate',
	'Nintendo translates as “Leave luck to heaven”.',
	'Prince\'s full name is Prince Rogers Nelson - he was named after the Prince Rogers Trio, his father\'s old jazz band.',
	'Saturn is not the only planet with rings. Jupiter, Uranus, and Neptune also have rings, although they are much fainter and less spectacular than Saturn\’s.',
	'Squirrel monkeys have at least twenty vocalizations',
	'The ancient Greeks believed that redheads would turn into vampires after they died.',
	'The best dog to reportedly attract a date is the Golden Retriever. The worst is the Pit Bull.',
	'The Black Eyed Peas\' “I Gotta Feeling” is more popular than any Elvis or Simon & Garfunkel song',
	'The blue whale can weigh nearly 200 tons and is the largest animal that has ever existed on the earth',
	'The dolphin’s most dangerous enemy is humans.',
	'The elephant is the only animal with 4 knees.',
	'The lips of bears are not attacked to their gums, which make their lips look rubbery.',
	'The maximum achievable score possible in a game of Pac-Man is 3,333,360 points.',
	'The sun contains 99.85% of the mass in the solar system.',
	'The sun rotates on its axis once every 25.38 Earth days or 609.12 hours.',
	'Wolf gestation is around 65 days. Wolf pups are born both deaf and blind and weigh only one pound.',
	'Wolves have about 200 million scent cells. Humans have only about 5 million. Wolves can smell other animals more than one mile (1.6 kilometers) away.',
	'Wolves run on their toes, which helps them to stop and turn quickly and to prevent their paw pads from wearing down.',
	'You cannot snore and dream at the same time.'
];

lists.food = [
	':apple:',
	':bot_snack:',
	':cake:',
	':cake:',
	':coffee:&:smoking:',
	':fish:',
	':fork_and_knife:',
	':hamburger:&:fries:',
	':hamster:',
	':icecream:',
	':mouse:',
	':ramen:',
	':rice:',
	':spaghetti:',
	':sushi:',
	':tangerine:'
];
